"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var sprint_controller_1 = require("../controllers/sprint.controller");
var auth_1 = require("../middleware/auth");
var orgAccess_1 = require("../middleware/orgAccess");
var projectAccess_1 = require("../middleware/projectAccess");
var validate_1 = require("../middleware/validate");
var sprint_validator_1 = require("../validators/sprint.validator");
var router = (0, express_1.Router)({ mergeParams: true });
router.use(auth_1.authenticate);
router.post("/", (0, orgAccess_1.orgAccess)(), (0, projectAccess_1.projectAccess)(["MANAGER"]), (0, validate_1.validate)(sprint_validator_1.createSprintSchema), sprint_controller_1.createSprint);
router.get("/", (0, orgAccess_1.orgAccess)(), (0, projectAccess_1.projectAccess)(), sprint_controller_1.listSprints);
router.get("/:sprintId", (0, orgAccess_1.orgAccess)(), (0, projectAccess_1.projectAccess)(), sprint_controller_1.getSprint);
router.patch("/:sprintId", (0, orgAccess_1.orgAccess)(), (0, projectAccess_1.projectAccess)(["MANAGER"]), (0, validate_1.validate)(sprint_validator_1.updateSprintSchema), sprint_controller_1.updateSprint);
router.delete("/:sprintId", (0, orgAccess_1.orgAccess)(), (0, projectAccess_1.projectAccess)(["MANAGER"]), sprint_controller_1.deleteSprint);
router.patch("/:sprintId/activate", (0, orgAccess_1.orgAccess)(), (0, projectAccess_1.projectAccess)(["MANAGER"]), sprint_controller_1.activateSprint);
router.patch("/:sprintId/complete", (0, orgAccess_1.orgAccess)(), (0, projectAccess_1.projectAccess)(["MANAGER"]), sprint_controller_1.completeSprint);
exports.default = router;
