"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var ticket_controller_1 = require("../controllers/ticket.controller");
var auth_1 = require("../middleware/auth");
var orgAccess_1 = require("../middleware/orgAccess");
var projectAccess_1 = require("../middleware/projectAccess");
var validate_1 = require("../middleware/validate");
var ticket_validator_1 = require("../validators/ticket.validator");
var router = (0, express_1.Router)({ mergeParams: true });
router.use(auth_1.authenticate);
router.post("/", (0, orgAccess_1.orgAccess)(), (0, projectAccess_1.projectAccess)(), (0, validate_1.validate)(ticket_validator_1.createTicketSchema), ticket_controller_1.createTicket);
router.get("/", (0, orgAccess_1.orgAccess)(), (0, projectAccess_1.projectAccess)(), ticket_controller_1.listTickets);
router.get("/:ticketId", (0, orgAccess_1.orgAccess)(), (0, projectAccess_1.projectAccess)(), ticket_controller_1.getTicket);
router.patch("/:ticketId", (0, orgAccess_1.orgAccess)(), (0, projectAccess_1.projectAccess)(), (0, validate_1.validate)(ticket_validator_1.updateTicketSchema), ticket_controller_1.updateTicket);
router.delete("/:ticketId", (0, orgAccess_1.orgAccess)(), (0, projectAccess_1.projectAccess)(["MANAGER"]), ticket_controller_1.deleteTicket);
router.patch("/:ticketId/assign", (0, orgAccess_1.orgAccess)(), (0, projectAccess_1.projectAccess)(), (0, validate_1.validate)(ticket_validator_1.assignTicketSchema), ticket_controller_1.assignTicket);
router.patch("/:ticketId/status", (0, orgAccess_1.orgAccess)(), (0, projectAccess_1.projectAccess)(), (0, validate_1.validate)(ticket_validator_1.changeStatusSchema), ticket_controller_1.changeStatus);
router.patch("/:ticketId/sprint", (0, orgAccess_1.orgAccess)(), (0, projectAccess_1.projectAccess)(["MANAGER", "DEVELOPER"]), (0, validate_1.validate)(ticket_validator_1.moveToSprintSchema), ticket_controller_1.moveToSprint);
exports.default = router;
